import Head from 'next/head'
import Home from "./home/";

import axios from 'axios';


export default function Index({productList,categoryList}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
        
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <Home productList={productList} categoryList={categoryList} />
      
    </div>
  )
}
export const getServerSideProps = async ()=>{
  const product = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/products`);
  const category = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/categories`);
  return{
    props:{
      categoryList: category.data? category.data:[],
      productList : product.data? product.data : [],
    },
  }
}

