import Head from "next/head";
import Home from "./home/";
import axios from 'axios';
import { useEffect, useState } from "react";

export default function Index({categoryList}) {
  const [productList, setProductList] = useState([]);
  useEffect(() => {
    const getProduct = async () => {
      try {
        const res = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/products`);
        setProductList(res?.data)
        
      } catch (error) {
        console.log(error);
      }
    };

    getProduct();
  }, []);
  return (
    <div>
      <Head>
        <title>Food Ordering</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com/" />
        <link rel="preconnect" href="https://fonts.gstatic.com/" crossOrigin />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home productList={productList} categoryList={categoryList} />
    </div>
  );
}
export const getServerSideProps = async () => {

  const category = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/categories`);
  return {
    props: {
      categoryList: category.data ? category.data : [],
    },
  };
};






